# GitHub Action workflow to build and run Impacket's tests
#

name: Build and test Impacket

on: [push, pull_request]

env:
  NO_REMOTE: true
  DOCKER_TAG: impacket:latests

jobs:
  test:
    name: Run unit tests and build wheel
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9]
        experimental: [false]
        include:
          - python-version: 2.7
            tox-env: py27
          - python-version: 3.6
            tox-env: py36
          - python-version: 3.7
            tox-env: py37
          - python-version: 3.8
            tox-env: py38
          - python-version: 3.9
            tox-env: py39
            experimental: true
    env:
      TOXENV: ${{ matrix.tox-env }}

    steps:
      - name: Checkout Impacket
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install flake8 tox -r requirements.txt

      - name: Check syntax errors
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Check PEP8 warnings
        run: |
          flake8 . --count --ignore=E1,E2,E3,E501,W291,W293 --exit-zero --max-complexity=65 --max-line-length=127 --statistics

      - name: Run unit tests
        run: |
          tox

      - name: Build wheel artifact
        run: |
          python setup.py bdist_wheel

  docker:
    name: Build docker image
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Impacket
        uses: actions/checkout@v2

      - name: Build docker image
        run: |
          docker build -t ${{ env.DOCKER_TAG }} .
