name: Build and Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:

    name: Package py to exe

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        #  os: [ ubuntu-latest ]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    runs-on: ${{ matrix.os }}


    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller impacket
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Package Artifacts
        run: |
          pyinstaller examples\wmiexec.py --onefile
        
      - uses: actions/upload-artifact@v2
        with:
          name: name-of-artifact
          path: dist/
